<?php

namespace App\Http\Controllers;

use App\Enums\TransactionAction;
use App\Http\Requests\SyncTransactionRequest;
use App\Models\Transaction;
use App\Models\TransactionCategory;
use App\Models\Wallet;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\DB;

class SyncController extends Controller
{
    /**
     * Sync a batch of transactions from the mobile client.
     *
     * Accepts a JSON payload containing an array of transactions generated by the
     * offline-first mobile app. Each transaction uses a client-generated ULID as its
     * primary key. The endpoint is idempotent: sending the same batch twice will not
     * mutate the wallet balance a second time.
     *
     * **Payload structure:**
     * ```json
     * {
     *   "transactions": [
     *     {
     *       "id": "01ARZ3NDEKTSV4RRFFQ69G5FAV",
     *       "wallet_id": "<ulid>",
     *       "transaction_category_id": "<ulid>",
     *       "amount": 50000,
     *       "name": "Lunch",
     *       "note": null,
     *       "created_at": "2026-04-29T12:00:00Z",
     *       "deleted_at": null
     *     }
     *   ]
     * }
     * ```
     *
     * **Balance mutation rules (resolved from category → type → action):**
     * - `addition` → wallet balance increased by amount
     * - `deduction` → wallet balance decreased by amount
     * - `neutral` → no balance change
     *
     * **Idempotency:**
     * - New transaction → apply balance mutation once.
     * - Same transaction, same amount → skip (no balance change).
     * - Same transaction, different amount → apply only the delta (new − old).
     * - `deleted_at` provided → soft-delete and reverse previous balance mutation.
     *   Sending `deleted_at` again for an already-deleted record is a no-op.
     *
     * @response 200 {"synced": 3, "skipped": 1}
     * @response 401 Unauthenticated
     * @response 422 {"message": "...", "errors": {...}}
     */
    public function transactions(SyncTransactionRequest $request): JsonResponse
    {
        $synced = 0;
        $skipped = 0;

        DB::transaction(function () use ($request, &$synced, &$skipped) {
            foreach ($request->validated('transactions') as $item) {
                /** @var Wallet $wallet */
                $wallet = Wallet::withoutGlobalScopes()
                    ->where('id', $item['wallet_id'])
                    ->lockForUpdate()
                    ->firstOrFail();

                /** @var TransactionCategory $category */
                $category = TransactionCategory::with('transactionType')
                    ->withoutGlobalScopes()
                    ->where('id', $item['transaction_category_id'])
                    ->firstOrFail();

                $action = $category->transactionType?->action;

                /** @var Transaction|null $existing */
                $existing = Transaction::withoutGlobalScopes()
                    ->withTrashed()
                    ->find($item['id']);

                $isClientDeleted = ! empty($item['deleted_at']);

                if ($existing === null) {
                    // ── Case A: Brand new transaction ──────────────────────────
                    $newBalance = $this->applyAction($wallet->balance, $action, (float) $item['amount']);

                    $transaction = new Transaction;
                    $transaction->id = $item['id'];
                    $transaction->user_id = $request->user()->id;
                    $transaction->wallet_id = $wallet->id;
                    $transaction->transaction_category_id = $category->id;
                    $transaction->amount = $item['amount'];
                    $transaction->name = $item['name'];
                    $transaction->note = $item['note'] ?? null;

                    if (! empty($item['created_at'])) {
                        $transaction->created_at = $item['created_at'];
                    }

                    $transaction->save();

                    $wallet->update(['balance' => $newBalance]);

                    if ($isClientDeleted) {
                        // Client already deleted it — reverse and soft-delete
                        $reversedBalance = $this->reverseAction($newBalance, $action, (float) $item['amount']);
                        $wallet->update(['balance' => $reversedBalance]);
                        $transaction->delete();
                    }

                    $synced++;
                } elseif ($isClientDeleted && ! $existing->trashed()) {
                    // ── Case D: Client soft-deleted a record that exists on server ──
                    $reversedBalance = $this->reverseAction($wallet->balance, $action, (float) $existing->amount);
                    $wallet->update(['balance' => $reversedBalance]);
                    $existing->delete();

                    $synced++;
                } elseif (! $isClientDeleted && ! $existing->trashed() && (float) $existing->amount !== (float) $item['amount']) {
                    // ── Case C: Amount changed — apply delta only ──────────────
                    $oldAmount = (float) $existing->amount;
                    $newAmount = (float) $item['amount'];

                    // Reverse old, apply new
                    $balanceAfterReverse = $this->reverseAction($wallet->balance, $action, $oldAmount);
                    $balanceAfterNew = $this->applyAction($balanceAfterReverse, $action, $newAmount);

                    $existing->update(['amount' => $newAmount]);
                    $wallet->update(['balance' => $balanceAfterNew]);

                    $synced++;
                } else {
                    // ── Case B: Idempotent — nothing to do ────────────────────
                    $skipped++;
                }
            }
        });

        return response()->json([
            'synced' => $synced,
            'skipped' => $skipped,
        ]);
    }

    /**
     * Apply a balance mutation based on the transaction action.
     */
    private function applyAction(float $balance, ?TransactionAction $action, float $amount): float
    {
        return match ($action) {
            TransactionAction::Addition => $balance + $amount,
            TransactionAction::Deduction => $balance - $amount,
            default => $balance,
        };
    }

    /**
     * Reverse a previously applied balance mutation.
     */
    private function reverseAction(float $balance, ?TransactionAction $action, float $amount): float
    {
        return match ($action) {
            TransactionAction::Addition => $balance - $amount,
            TransactionAction::Deduction => $balance + $amount,
            default => $balance,
        };
    }
}
